using System;
using System.Collections.Generic;

namespace prjFinalProjectApi.Models;

public partial class EmployeeAnnualLeaveBalance
{
    public int BalanceId { get; set; }

    public int? EmployeeId { get; set; }

    public int? BalanceYear { get; set; }

    public decimal? TotalDays { get; set; }

    public decimal? UsedDays { get; set; }

    public bool? AutoGenerated { get; set; }

    public DateTime? LastUpdated { get; set; }
}
